# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  fork:
    branches: ["main"]
  schedule:
    - cron: "0 17 * * *"
  # 手动触发事件
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.4"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python
        env:
          JUEJIN_COOKIE: ${{ secrets.JUEJIN_COOKIE }}
          JUEJIN_SENDKEY: ${{ secrets.JUEJIN_SENDKEY }}
          JUEJIN_DATA: ${{ secrets.JUEJIN_DATA }}
        run: |
          python ./juejin.py
